apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-getter
  labels:
    app: gist-getter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gist-getter
  template:
    metadata:
      labels:
        app: gist-getter
    spec:
      containers:
        - name: ee-container
          image: ee:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gist-getter-service
  labels:
    app: gist-getter
spec:
  selector:
    app: gist-getter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
