apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-getter
  labels:
    app: gist-getter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gist-getter
  template:
    metadata:
      labels:
        app: gist-getter
    spec:
      containers:
        - name: ee-container
          image: ee:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          command: ["/bin/bash", "-c"]
          args: ["uvicorn app.main:app --host 0.0.0.0 --port 8080"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gist-getter-service
  labels:
    app: gist-getter
spec:
  selector:
    app: gist-getter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
